// Generated by CoffeeScript 1.7.1
(function() {
  test("leafJs should be loaded", function() {
    console.assert(Leaf);
    console.assert(Leaf.Widget);
    console.assert(Leaf.EventEmitter);
    return ok(!!Leaf);
  });

}).call(this);
