// Generated by CoffeeScript 1.8.0
(function() {
  describe("test template manager", function() {
    return it("test load nested template", function(done) {
      var tm;
      tm = new Leaf.TemplateManager();
      tm.use("parent/child");
      tm.start();
      return tm.on("ready", function(templates) {
        console.log(templates);
        return done();
      });
    });
  });

}).call(this);
