// Generated by CoffeeScript 1.8.0
(function() {
  describe("test TemplateManager", function() {
    return it("basic test", function(done) {
      var tm;
      tm = new Leaf.TemplateManager();
      return done();
    });
  });

}).call(this);
